### ISSUE TITLE
Private modules checkout failed with actions/checkout@v2

### ISSUE THREAD

**Issue by ray-x** [mvdan/github-actions-golang#15]
After configuring the ci.yml to this:

```
env:
  GOPRIVATE: "github.com/company"
jobs:
.....
  - name: Check out code into the Go module directory
     uses: actions/checkout@v2

  - name: Configure git for private modules
    env:
      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    run: git config --global url."https://YOUR_GITHUB_USERNAME:${TOKEN}@github.com".insteadOf "https://github.com"
```
I am still saw following error:
```
go: github.com/company/repo@v0.0.0-20210104011042-bad989a6d7f2: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/runner/go/pkg/mod/cache/vcs/4902ad5423d70bf8a819e419fc1d6e0667f5a8f1542bd02ff6253926ac8fcb35: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/company/repo/' not found
Error: Process completed with exit code 1.
```
If I change ` uses: actions/checkout@v2` to ` uses: actions/checkout@v1` seems solve the issue

Is there additional setup required for checkout@v2?

**Comment by mvdan** [comment]
I honestly don't know. This sounds like a bug that you should report to the https://github.com/actions/checkout repo.

**Comment by mvdan** [comment]
I'm going to close this for now. If you talk to anyone at GitHub and find what was wrong, I'd be happy to hear.

**Comment by shakefu** [comment]
For future folks who come across this, you need to configure the [GOPRIVATE](https://golang.org/ref/mod#private-module-privacy) environment variable as well.
