### ISSUE TITLE
How to use shields with github actions ?

### ISSUE THREAD

**Issue by chmike** [mvdan/github-actions-golang#19]
I have some projects using travis and this allowed me to  have shields when the project passed. 

How can we do this with github actions ?

BTW, thank you very much for your helpful project.

**Comment by pellared** [comment]
Take a look here: https://shields.io/category/build and find `GitHub Workflow status`.

I have created some bagdes at https://github.com/golang-templates/seed

**Comment by mvdan** [comment]
See https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge.

You're not the first person to ask this, so I'll add it.
