### ISSUE TITLE
Testing for Go v1 apps without go mod

### ISSUE THREAD

**Issue by suntong** [mvdan/github-actions-golang#21]
Is it possible to test for Go v1 apps that's not having/using go mod?

This is what I'm getting --
https://github.com/suntong/shuttlebot/runs/2701444155?check_suite_focus=true

```
Run go test ./...
main.go:16:2: cannot find package "github.com/caarlos0/env" in any of:
	/opt/hostedtoolcache/go/1.15.12/x64/src/github.com/caarlos0/env (from $GOROOT)
	/home/runner/go/src/github.com/caarlos0/env (from $GOPATH)
logging.go:8:2: cannot find package "github.com/go-kit/kit/log" in any of:
	/opt/hostedtoolcache/go/1.15.12/x64/src/github.com/go-kit/kit/log (from $GOROOT)
	/home/runner/go/src/github.com/go-kit/kit/log (from $GOPATH)
. . .
```

Would it be possible that I set my own `GOPATH` and do `go get` myself?

**Comment by mvdan** [comment]
If you do want to use GOPATH mode, see https://github.com/mvdan/github-actions-golang#how-do-i-set-up-a-gopath-build.
