### ISSUE TITLE
GOPATH: ${{ runner.workspace }} Do not work with actions

### ISSUE THREAD

**Issue by alonyb** [mvdan/github-actions-golang#3]
I used your template for set GOPATH env variable, but there is an error.

`- Your workflow file was invalid: The pipeline is not valid. .github/workflows/go.yml (Line: 9, Col: 15): Unrecognized named-value: 'runner'. Located at position 1 within expression: runner.workspace,.github/workflows/go.yml (Line: 26, Col: 7): Unexpected value 'with'
`

My line 9 has:
`GOPATH: ${{ runner.workspace }}`

**Comment by mvdan** [comment]
Hm, maybe they've changed the syntax a bit. I'm pretty sure this worked in the past. If you want to investigate or send a patch, feel free - otherwise I might get to it later this week.
