### ISSUE TITLE
Adding GOBIN to PATH

### ISSUE THREAD

**Issue by francislavoie** [mvdan/github-actions-golang#6]
First, I just wanted to say, huge thanks for this repo/README, it helped me a ton. I've been working on [setting up github actions for Caddy](https://github.com/caddyserver/caddy/pull/3152).

In your README, you note:

> The setup-go action doesn't set PATH, so currently it's not possible to go install a program and run it directly. Until that's fixed, consider absolute paths like $(go env GOPATH)/bin/program.

I just wanted to point out that I figured out that you can just do this on any step after `setup-go`, pretty much entirely smoothes that issue over:

```bash
echo "::add-path::$(go env GOPATH)/bin"
```

**Comment by mvdan** [comment]
Yeah, I've seen similar magic before, but I initially preferred to stick to documented features :)

We can add it though, since there still isn't an official portable way to do this.

**Comment by francislavoie** [comment]
Well, it is documented: https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path

Thanks for adding it to the README!

**Comment by mvdan** [comment]
Ah, my bad! It wasn't documented when I last looked :)
