### ISSUE TITLE
docs: `platform` should be `os`

### ISSUE THREAD

**Issue by ghostsquad** [mvdan/github-actions-golang#8]
in your readme, it specifies to use `platform`, but it should be `os`.

```
platform: [ubuntu-latest, macos-latest, windows-latest]
```

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-running-with-more-than-one-operating-system

**Comment by mvdan** [comment]
Interesting; I don't think this matters as it's just a variable name. It seems like the docs and examples used to use `platform`, and now they're switching to `os`. That's shorter and perhaps less confusing, so I agree it's a good idea to change them. Do you want to send a PR?

**Comment by ghostsquad** [comment]
I mention it because I tried by copying and pasting, and it never triggered. I don't think it's a user-defined variable name. It's specifically part of the "matrix" schema.

**Comment by ghostsquad** [comment]
Ya, I see now that your workflow uses platform, and it works. And now I see why you mentioned it being a variable name. I'm not entirely sure why it didn't work for me, but I guess at minimum, this now matches the docs! so win win.
